### ISSUE TITLE
how to center entities if they're only 2

### ISSUE THREAD

**Issue by JPOliveGit** [nervetattoo/banner-card#105]
is it possible to center the entities if only using 2

<img width="503" alt="Captura de ecrã 2021-04-03, às 17 59 00" src="https://user-images.githubusercontent.com/13860407/113485598-5830b080-94a6-11eb-9879-da23041c2b50.png">

**Comment by bcmitri** [comment]
You can set the row_size to 2.

**Comment by JPOliveGit** [comment]
thks I didn't see that info anywhere awesome, another question or if you want I can open another issue is there anyway to make the text centered

![IMG_4533](https://user-images.githubusercontent.com/13860407/113597730-09b11c80-9634-11eb-9c6d-2285eeff4369.jpg)

**Comment by bcmitri** [comment]
I’ve noticed that issue when the text is too big for that section. For me, the solution was to find a way to shorten the text in the affected section, or to expand the section.

**Comment by JPOliveGit** [comment]
I used cardmod to reduce the font size... just not to change all the values defined from LG
