### ISSUE TITLE
Arrow up/down in cover component

### ISSUE THREAD

**Issue by sti0** [nervetattoo/banner-card#11]
If the cover is completely opened or closed the button arrow up / down should by greyed out and should be not clickerable at all. Like it is in "Vanilla" HA

![image](https://user-images.githubusercontent.com/18382402/58592744-6b9ae100-8269-11e9-98e0-dcf5a5231d7f.png)

**Comment by iantrich** [comment]
I just added this card and wanted the same thing. Want to take a look at this code base so might see about adding this feature 😁

**Comment by nervetattoo** [comment]
There's already a PR for it in #8 that will be part of the next release, along with a number of other stuff :D

**Comment by iantrich** [comment]
😎
