### ISSUE TITLE
CSS Theming Syntax

### ISSUE THREAD

**Issue by aptonline** [nervetattoo/banner-card#13]
Thanks for adding the documentation for the CSS theming but again I can't seem to get this to work.  Can you give an example?

**Comment by nervetattoo** [comment]
Sorry, I don't do theming myself as I prefer sticking to stock. I know you can easily do it with `card-modder` and just set those specific variables that is listed in the docs.
Perhaps someone else can chime in regards to actual HA themes.

**Comment by aptonline** [comment]
Ah sorry I thought the styling was built into the card didnt realise it needed external support.

**Comment by kalkih** [comment]
Yeah, I tried to set the css vars in my theme but the card override them, would be great if we could set the css variables in our theme.

The way I handle this in my cards is by using one "external" variable and one "internal" variable.
The "internal" variable is set by the "external" variable if existing, if not, it's set to the default value.
Not sure if this is the optimal solution, but it does the trick.

https://github.com/kalkih/mini-media-player/blob/master/src/style.js#L6-L9

**Comment by kajmaj** [comment]
Card modder works like a charm :)
