### ISSUE TITLE
Posibility to hide header

### ISSUE THREAD

**Issue by matisaul** [nervetattoo/banner-card#15]
Hi! First of all, thanks for this great card!

Is there a change to add the posibility to don't show any header, and just put the sensors?

**Comment by tillbaks** [comment]
You can hide it by setting `heading: false` in the lovelace config.
Should probably be added in the documentation. :)

**Comment by nervetattoo** [comment]
I'll leave this open for an external PR to amend it to the docs, a good issue for someone to get their feet wet.

**Comment by JoelLau** [comment]
@nervetattoo thanks for leaving it up! I would like to take on the documenting this
