### ISSUE TITLE
Bug with group toggle

### ISSUE THREAD

**Issue by valounours** [nervetattoo/banner-card#19]
Hi,

With group i just see "off" or "on" not the toggle button...

Missing feature or bug ?

Thk's

P.S : Sorry for my english

**Comment by nervetattoo** [comment]
The `group` domain has no special support to render toggles as of now. A PR would be welcome here.

**Comment by nervetattoo** [comment]
I'm guessing you can set `domain: light` (or another domain that is toggle-able) and it would probably work. Let me know if that works.

**Comment by ngsmits** [comment]
Thanks nervetattoo for your feedback. You're workaround solved this issue for me
