### ISSUE TITLE
Feature request: map_state icon color 

### ISSUE THREAD

**Issue by friendodevil** [nervetattoo/banner-card#24]
Please add the capability to change icon color in map_state. This is important when changing state. It will be very useful 

Thanks

**Comment by IIStevowII** [comment]
I'm also interested in this issue, because i'm currently experiencing the same problem.

I was wondering if there was a specific design choice for going for <paper-icon-button /> instead of <ha-icon /> when rendering? My only guess would be because of a possible action, but <ha-icon /> also supports an click event.

As <ha-icon /> supports an active state color, and is also automatically supported by theming, I'd say that would be the easiest/most clean solution to this problem? Ofcourse I don't know the history...

**Comment by friendodevil** [comment]
right, would be great if color can be supported per button like when using Button-Card ( https://github.com/custom-cards/button-card)

**Comment by IIStevowII** [comment]
I've created above PR which makes use of the official `ha-icon` component. This component already uses different colors for active state. You can also use this in theming to customize to your need, just use the css variable `--paper-item-icon-active-color`

Depending on the vision of @nervetattoo you might want to try [card-mod](https://github.com/thomasloven/lovelace-card-mod) for extended coloring purposes.

If he wants to add this kind of customization possibilities to the component itself, that would require a bit more work.

**Comment by wiuwiu** [comment]
I'm also interested in. It will be great to have an icon color depend on its state.

**Comment by WhistleMaster** [comment]
Any news related to @IIStevowII PR merged to the repository ?

**Comment by IIStevowII** [comment]
The PR is still open, waiting for approval.

**Comment by nervetattoo** [comment]
I'm considering this. Problem is that I do not want this behavior myself, I prefer either changing icons based on state or simply using toggles. Active state color doesn't always work too well with the banner-card colors at least I choose. 

Regarding using `paper-icon-button` @IIStevowII , I think my intention was to not have proper support for icons and buttons.

**Comment by WhistleMaster** [comment]
Maybe that could be an option, true or false, to show state color or not ?

**Comment by IIStevowII** [comment]
> Maybe that could be an option, true or false, to show state color or not ?
It would certainly be possible to either choose ha-icon or paper-icon-button depending on a certain option.

**Comment by friendodevil** [comment]
for dashboards its valuable to change icon based on state e.g.: ligh off (grey) light on (yellow)

**Comment by WhistleMaster** [comment]
Could it be added through #33 ?

**Comment by WhistleMaster** [comment]
Any news regarding this issue ? Thanks !

**Comment by nervetattoo** [comment]
Basic support for map_state based control is added and will be in the next version
