### ISSUE TITLE
Cover arrows greyed out if not fully open / closed

### ISSUE THREAD

**Issue by sti0** [nervetattoo/banner-card#31]
Related to #8 

The cover arrows now visible and greyed out, but if the cover is closed for example to 20%, the up button is still greyed out while the down button is white. So its possible to close the cover fully and then open it again.

To solve this problem, the attribute current_position should be checked instead of the state of the entity.

Banner Card:
![image](https://user-images.githubusercontent.com/18382402/61494141-ae4d7f80-a9b5-11e9-83a3-c0df4d81729c.png)
Home Assistant:
![image](https://user-images.githubusercontent.com/18382402/61494162-bc9b9b80-a9b5-11e9-86ef-b87b89f0c0f5.png)

**Comment by jrhbcn** [comment]
I am experiencing the same issue. Button up is greyed out using the latest release (0.5.0). My covers do not report position (they are a template with only commands to open / close / stop and "position_template: 50" so both open/close buttons should be available). As reported by @sti0 they are not greyed in normal home assistant lovelace.

**Comment by l0ghan** [comment]
I'll check it out :)

**Comment by sti0** [comment]
@l0ghan did you any progress?

**Comment by fastcolors** [comment]
#56 fixes it (or at least you can use my fork for now until the proper fix is done ;-) )

**Comment by soloam** [comment]
I still have this problem! I was going to repor it, but found this report!

**Comment by ViperRNMC** [comment]
i have also problem with cover, don't see the arrows at all

**Comment by roussell** [comment]
Did this bug resurface? I'm running 0.111.4 with roller blinds that don't report position (RF using a Broadink Pro). If I stop the shade before it reaches the limit in either direction, I can't continue in that direction until I move the shade in the opposite direction, stop it, and then can move it in the intended direction. This is purely a UI thing as the direction can move however I need from service calls, automations, etc.

**Comment by JC-LB** [comment]
I have some shutter where I use this to avoid greying out in lovelace:
`
**customize**
cover.volet_cuisine:
  assumed_state: true`

But it's not taken in account by banner-card.

**Comment by airampg** [comment]
Hi, I have this same issue. Has any progress been made on fixing this? My cover does not report a state as it is done with ESPHome and if they are stopped in the middle this card wont register it. The normal lovelace cards shows both arrows available.
 
![image](https://user-images.githubusercontent.com/41060873/120208744-be774c80-c225-11eb-8b66-1365c9ca3720.png)

**Comment by JohannCR** [comment]
@airampg Same problem here. 
What do you mean by "normal lovelace card" ?

**Comment by airampg** [comment]
> @airampg Same problem here. What do you mean by "normal lovelace card" ?

Hi JohannCR. It has been a while, but I think I meant the entity card.
