### ISSUE TITLE
Help: How to adjust the heading

### ISSUE THREAD

**Issue by sasukebinbin** [nervetattoo/banner-card#38]
I’d like to adjust the height of the heading. 
Because I hope there is no much blank lines above and below the title in heading.
So the card height can be reduce. 
I believe this can do so by edit some codes.
But I’m not family with CSS.
Could you give me a help? 
Thanks

**Comment by Pirol62** [comment]
would be interested as well

**Comment by nervetattoo** [comment]
[Please see the readme under CSS vars for theming](https://github.com/nervetattoo/banner-card#css-vars-for-theming)
I've now included some links to the official docs on how to do themes and since the 0.6 release theming should work well with the card as well.
