### ISSUE TITLE
Feature Request: template / icons in title

### ISSUE THREAD

**Issue by WhistleMaster** [nervetattoo/banner-card#39]
It would be a nice feature to be able to add some info in the title, using template and icons such as the following mock-up made by a Reddit user:

![ayseis5zhgf31](https://user-images.githubusercontent.com/1544568/62820262-2ac12180-bb62-11e9-876f-d7252145798c.png)

**Comment by Pirol62** [comment]
Very goog idea. That saves space on the mobile screen.

**Comment by nervetattoo** [comment]
Thanks for the request, I'll be closing this as a duplicate of #20 though to keep further discussion there. Please link to the reddit thread in question there if possible @WhistleMaster !

**Comment by WhistleMaster** [comment]
Sure, I've just linked it in the reddit thread.

**Comment by bakazm** [comment]
I'm the one who made the original mockup. I have been able to mostly create a functional version of the image with the following cards: 'custom:vertical-stack-in-card', 'custom:mini-media-player', and a 'picture-elements'. It's definately hobbled together, but it works. A functional card that can be set up using the UI would be great!

**Comment by shlatchz** [comment]
> I'm the one who made the original mockup. I have been able to mostly create a functional version of the image with the following cards: 'custom:vertical-stack-in-card', 'custom:mini-media-player', and a 'picture-elements'. It's definately hobbled together, but it works. A functional card that can be set up using the UI would be great!

@bakazm can you please share it?
