### ISSUE TITLE
Enable switch representation as light entity

### ISSUE THREAD

**Issue by l0ghan** [nervetattoo/banner-card#4]
Hello,

I'm not an expert but I've done some modification in order to enable switch in your module with some modifications
What do you think ? it can be added ? 
I really enjoy the work and want to help you if I can do anything :)

regards
julien

**Comment by nervetattoo** [comment]
I noticed you had already started 👍 
Please open a PR and I'll review it. I added just lights to start with as that was my crucial need, but were hoping someone would pick it up and add other domains.
I have some work towards media_player going and would love to merge your work first as I need to refactor some stuff and don't want to burden you with changing your implementation that much!

**Comment by l0ghan** [comment]
PR just submitted :)
if I can help in any way you just have to ask
regards
julien

**Comment by nervetattoo** [comment]
Merged and to be published soon
