### ISSUE TITLE
Automatic dark / light text

### ISSUE THREAD

**Issue by WhistleMaster** [nervetattoo/banner-card#41]
Hi !

I tried to use the new feature from v0.7 to have automatically the light or dark text in the heading with a black background but it does not seem to work for me.

<img width="1330" alt="Screenshot 2019-08-18 at 10 25 29" src="https://user-images.githubusercontent.com/1544568/63222065-9f1f4480-c1a2-11e9-82cb-01f137f132bf.png">
<img width="404" alt="Screenshot 2019-08-18 at 10 25 46" src="https://user-images.githubusercontent.com/1544568/63222066-9f1f4480-c1a2-11e9-9f31-790c7e5940dd.png">

**Comment by nervetattoo** [comment]
What is your color code for background? It only works for hex colors

**Comment by WhistleMaster** [comment]
Indeed, I used the color name instead of the hex color. I tried to use the hex code for black and it works. 

I tried to use a dark blue, but the text stays black:

![image](https://user-images.githubusercontent.com/1544568/63228268-d6b4dd80-c1f0-11e9-994d-bb950c4b3374.png)

**Comment by WhistleMaster** [comment]
Feature for text color added in v.0.8.0, thanks !

**Comment by WhistleMaster** [comment]
Unfortunately, I've updated to v.0.8.1 but it still does not work. Seems that the change has not been applied.

`static get properties(){return{config:Object,gridSizes:Array,entities:Array,entityValues:Array,rowSize:Number,_hass:Object}`

<img width="268" alt="Screenshot 2019-08-20 at 18 01 17" src="https://user-images.githubusercontent.com/1544568/63363749-78b10300-c374-11e9-9364-7a102a237124.png">

**Comment by nervetattoo** [comment]
Strange. I did confirm it working for me before publishing at least. Anyone else can confirm working/not working?

**Comment by WhistleMaster** [comment]
This is what I'm using:

<img width="991" alt="Screenshot 2019-08-22 at 19 34 26" src="https://user-images.githubusercontent.com/1544568/63536409-d3349580-c513-11e9-9b9a-c70e0132dc0b.png">

**Comment by WhistleMaster** [comment]
The problem seems to be with HACS I think. The `banner-card.js` file installed by HACS has the following function: 

`get properties(){return{config:Object,gridSizes:Array,entities:Array,entityValues:Array,rowSize:Number,_hass:Object}}`

which does not have the changes regarding the text color.

**Comment by WhistleMaster** [comment]
I tried to remove all files from /www/community/banner-card and downloaded the latest release from github, it works !

But as soon as I'm using HACS to install Banner-card, I don't get the latest release...
