### ISSUE TITLE
Blinds button greyed out 

### ISSUE THREAD

**Issue by darox** [nervetattoo/banner-card#47]
Many thanks for creating such a nice component. I love the design, however I'm facing some issues. The up blinds button is greyed out and this is only happening with this component. See attached picture. 
https://imgur.com/a/C7HDZbI

**Comment by sti0** [comment]
Duplicate to https://github.com/nervetattoo/banner-card/issues/31

**Comment by fastcolors** [comment]
#56 fixes it
