### ISSUE TITLE
Light icons not showing up

### ISSUE THREAD

**Issue by chansters** [nervetattoo/banner-card#53]
Everything was working great but recently the icons for any light entities are not showing up.  Any suggestions on how to fix this ? 

![IMG_159A5314D6D4-1](https://user-images.githubusercontent.com/8441205/66970944-13ac1d80-f044-11e9-81d3-339bf50e6c4b.jpeg)

![IMG_02E11A89A655-1](https://user-images.githubusercontent.com/8441205/66970925-02631100-f044-11e9-8781-ea21e6bb7609.jpeg)

**Comment by gohassgo** [comment]
Upgrade to 0.9.0.

**Comment by chansters** [comment]
Just upgraded but the light icons are still not showing up.  I'm on HA 0.100.2.

**Comment by imMrRAW** [comment]
Same here - Updated to latest version of Banner Card and using Home Assistant
0.100.2

No switches showing!

**Comment by patrik996** [comment]
Same issue here. Using HASS 0.100.2 and banner-card 0.9.0 using HACS.
Downgraded to 0.8.1 and the switches appear again. Something is up with 0.9.0.

**Comment by atskj** [comment]
Same issue. But showed up after I emptied the cache..

**Comment by patrik996** [comment]
Yep seems to be solved when cache is empied. I changed back to 0.9.0 and the issue was resolved.

**Comment by chansters** [comment]
How do I empty the cache of the Home Assistant iOS app ?
