### ISSUE TITLE
mdi icon not working in header

### ISSUE THREAD

**Issue by aaewalsh** [nervetattoo/banner-card#63]
Hey @nervetattoo 

I'm have issues with the latest update. the mdi Icon set doesn't seem to be recognized.

Version Installed: 0.10.0

![image](https://user-images.githubusercontent.com/54256281/73022059-0ee6ca80-3de6-11ea-9734-a711cee62863.png)

Please Help!!

Code Used:

`type: 'custom:banner-card'
heading:
  - 'mdi:shower'
  - Bathroom
row_size: 4
background: pink
entities:
  - entity: sensor.sensenode_temp_spare_bedroom
    name: Temperature
  - entity: sensor.sensenode_humidity_spare_bedroom
    name: Humidity
  - entity: sensor.sensenode_lux_spare_bedroom
    name: Lux
  - entity: binary_sensor.sensenode_motion_spare_bedroom
    map_state:
      'off': 'mdi:walk'
      'on': 'mdi:run'
    name: Motion`

**Comment by nervetattoo** [comment]
Please confirm the developer tools console actually displays `banner-card: 0.10.0`. This is most likely a browser cache issue

**Comment by nervetattoo** [comment]
I'm very certain this is a cache issue and will close until someone can reproduce while also seeing the console output

**Comment by WhistleMaster** [comment]
Seems that there is a release issue. File referenced as 0.10.0 is in fact 0.9.0

See: https://github.com/nervetattoo/banner-card/issues/68#issuecomment-609374537
