### ISSUE TITLE
input_boolean show as a ON/OFF sensor

### ISSUE THREAD

**Issue by vitinhosessa** [nervetattoo/banner-card#9]
I use the input_boolean as a switch, how do i make to appear as a switch?

**Comment by nervetattoo** [comment]
That's not supported right now but its quite easy to add. Will see what I can do soon

**Comment by kethoth** [comment]
As a temporary workaround, tapping/clicking the input Boolean brings up more info with a toggle switch.

**Comment by CatMonster** [comment]
Also ```.toggle``` like script.toggle or switch.toggle shows as a ON/OFF button

**Comment by nervetattoo** [comment]
For now you should at least be able to use the [action feature to solve these types of setups](https://github.com/nervetattoo/banner-card#using-entity-action)
